# Generated by Django 5.0.1 on 2024-01-31 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='activee',
            new_name='active',
        ),
    ]
